### ISSUE TITLE
Slight Typo

### ISSUE THREAD

**Issue by gep13** [skaterdav85/ember-data-in-the-wild#1]
Chapter 5 - Page 30

Normalizing Responses:

![image](https://cloud.githubusercontent.com/assets/1271146/23804600/7d5d45a8-05b2-11e7-8558-52658d36a6e0.png)

Should be `This format is...`

**Comment by iamdtang** [comment]
Thanks! I will make an update! :)

**Comment by iamdtang** [comment]
Just published the fix. Thanks again!

**Comment by gep13** [comment]
@skaterdav85 not a problem at all.  Do you know if I will get a notification about the change to the book?  Or how does that part work?  Thanks!

**Comment by iamdtang** [comment]
@gep13 I usually only notify everyone if there are significant changes. If I do some minor rewording or fix spelling mistakes, I don't notify everyone when I publish it. Maybe I should though. What do you think?

**Comment by gep13** [comment]
>@skaterdav85 said...
What do you think?

Honestly not sure.  It was more of a curiousity question than anything.  i.e. does the act of you making a change to the book push out a notification, or is this something that you do through the leanpub UI?  This afternoon I got a notification about an update to the book.

For something as trivial as this change, it might not be worthy of an update, but if there has been more fundamental changes, then a notification would be very useful.  Also, it would be good to know what changes have been made since perhaps you last read the book.

**Comment by iamdtang** [comment]
Sounds like we're on the same page :)
