### ISSUE TITLE
Formatting problem in PDF Version

### ISSUE THREAD

**Issue by gep13** [skaterdav85/ember-data-in-the-wild#2]
Chapter 6, page 50:

![image](https://cloud.githubusercontent.com/assets/1271146/23857188/4827f2f4-07f4-11e7-98a4-e20f2263cede.png)

The formatting in this section seems to be a little off.

**Comment by iamdtang** [comment]
Thanks! Trying to figure out a fix.

**Comment by iamdtang** [comment]
Fixed and published!
